/*
 * MCAL_TIMER1_CONFIG.h
 *
 *  Created on: Oct 28, 2023
 *      Author: mohamed
 */

#ifndef MCAL_MCAL_TIMER1_TIMER1_HEADERS_MCAL_TIMER1_CONFIG_H_
#define MCAL_MCAL_TIMER1_TIMER1_HEADERS_MCAL_TIMER1_CONFIG_H_



#endif /* MCAL_MCAL_TIMER1_TIMER1_HEADERS_MCAL_TIMER1_CONFIG_H_ */
